export const baseStyles = {
    "Food & Dining": { iconBackgroundColor: "#fdd5d7", iconColor: "#fd3c4a", iconName: "restaurant" },
    "Shopping": { iconBackgroundColor: "#fceed4", iconColor: "#fcac12", iconName: "cart" },
    "Transportation": { iconBackgroundColor: "#f5f5f5", iconColor: "#6c757d", iconName: "car-sport" },
    "Entertainment": { iconBackgroundColor: "#fff3cd", iconColor: "#ff9800", iconName: "film" },
    "Healthcare": { iconBackgroundColor: "#e3f2fd", iconColor: "#2196f3", iconName: "medkit" },
    "Rent & Bills": { iconBackgroundColor: "#e6f7ff", iconColor: "#007bff", iconName: "home" },
    "Travel": { iconBackgroundColor: "#e8f5e9", iconColor: "#4caf50", iconName: "airplane" },
    "Education": { iconBackgroundColor: "#ede7f6", iconColor: "#673ab7", iconName: "school" },
    "Investments": { iconBackgroundColor: "#d0f0c0", iconColor: "#388e3c", iconName: "trending-up" },
    "Salary": { iconBackgroundColor: "#d4edda", iconColor: "#28a745", iconName: "wallet" },
    "Business": { iconBackgroundColor: "#cce5ff", iconColor: "#007bff", iconName: "briefcase" },
    "Freelancing": { iconBackgroundColor: "#e9ecef", iconColor: "#6c757d", iconName: "laptop" },
    "Overtime Pay": { iconBackgroundColor: "#f3e5f5", iconColor: "#9c27b0", iconName: "timer" },
    "Bonuses and Incentives": { iconBackgroundColor: "#fff3cd", iconColor: "#ff9800", iconName: "gift" },
    "Stock Dividends": { iconBackgroundColor: "#c8e6c9", iconColor: "#4caf50", iconName: "bar-chart-outline" },
    "Rental Income (from property)": { iconBackgroundColor: "#e0f7fa", iconColor: "#0097a7", iconName: "building" },
    "Cryptocurrency Gains": { iconBackgroundColor: "#f5f5f5", iconColor: "#ff5722", iconName: "cash" },
    "Child Support/Alimony": { iconBackgroundColor: "#ffecb3", iconColor: "#ff9800", iconName: "people" },
    "Scholarships/Grants": { iconBackgroundColor: "#e3f2fd", iconColor: "#1565c0", iconName: "school" },
    "Royalties": { iconBackgroundColor: "#ede7f6", iconColor: "#673ab7", iconName: "musical-notes" },
    "Lottery or Gambling Winnings": { iconBackgroundColor: "#f5e6e6", iconColor: "#dc3545", iconName: "dice" },
    "Gifts or Donations Received": { iconBackgroundColor: "#e2f3e4", iconColor: "#28a745", iconName: "heart" },
    "Income from Side Hustles": { iconBackgroundColor: "#fce4ec", iconColor: "#e91e63", iconName: "hammer" },
    default: { iconBackgroundColor: "#f0f0f0", iconColor: "#6c757d", iconName: "help-circle" },
  };